export enum ModelType {
    ADMIN_GROUP = 'ADMIN_GROUP',
    BASE_GROUP = 'BASE_GROUP',
    COMMON_GROUP = 'COMMON_GROUP',
    PRIVILEGE_GROUP = 'PRIVILEGE_GROUP',
    USER = 'USER',
    USER_RESOURCE = 'USER_RESOURCE',
    UNKNOWN = 'UNKNOWN'
}