name: Build and analyze
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 12 * * 5'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'tags of manualy started action'  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
      - name: Checkout users ui
        uses: actions/checkout@v3
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: clean install build
        run: |
          npm ci
          npm run build
      - name: test
        run: npm run test -- --code-coverage --watch=false
      - name: sonar analysis
        env:
          GITHUB_TOKEN: ${{ secrets.APE_DEPENDENCY_BUILD_PAT }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: > 
          npm run sonar --
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.token=${{ secrets.SONAR_TOKEN }}
          -Dsonar.organization=ma-vin
          -Dsonar.projectKey=Ma-Vin_ape-users-ui
          -Dsonar.projectName=ape-users-ui
          -Dsonar.projectVersion=1.0
          -Dsonar.sourceEncoding=UTF-8
          -Dsonar.sources=src
          -Dsonar.exclusions=**/node_modules/**
          -Dsonar.tests=src
          -Dsonar.test.inclusions=**/*.spec.ts
          -Dsonar.javascript.lcov.reportPaths=coverage/users-ui/lcov.info
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: [ 'typescript' ]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}
    - name: Autobuild
      uses: github/codeql-action/autobuild@v2
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2